import {
  EVIDENCE_ACCOUNTS,
  EVIDENCE_BEATS,
  EVIDENCE_TOKEN,
  evidenceElapsedSeconds,
  evidenceOffsetSeconds,
  hashscanUrl,
} from "~~/lib/onboarding";

/**
 * The three-beat proof: the same transfer failing, the kit associating, the
 * same transfer succeeding.
 *
 * A Server Component with no client JavaScript. Every value comes from
 * `lib/onboarding/evidence.ts`, which is transcribed from EVIDENCE.md and
 * regenerated by `yarn hardhat:evidence`. Nothing here is illustrative and
 * nothing is computed for effect — the elapsed time is subtracted from the
 * consensus timestamps at render.
 *
 * Every row links to HashScan so a reader never has to take it on trust. That
 * is the whole reason this component exists: the argument for the template is
 * not a claim, it is three transaction ids.
 */
export const ProofOfAssociation = () => {
  const elapsed = evidenceElapsedSeconds();

  return (
    <section aria-labelledby="proof-heading">
      <div className="flex items-baseline justify-between flex-wrap gap-2 mb-1">
        <h2 id="proof-heading" className="text-xl font-bold">
          The same transfer, before and after
        </h2>
        <span className="badge badge-sm font-mono">{elapsed}s apart</span>
      </div>
      <p className="text-sm opacity-70 mb-4">
        Three real transactions on Hedera testnet, {elapsed} seconds apart, in consensus order. The only thing that
        changed between the first and the last is that the kit associated the token. Every row links to HashScan —
        check them rather than believing them.
      </p>

      <ol className="flex flex-col gap-3 list-none pl-0">
        {EVIDENCE_BEATS.map(beat => {
          const offset = evidenceOffsetSeconds(beat);
          return (
            <li key={beat.transactionId}>
              <div
                className={`card border-2 ${
                  beat.phase === "before"
                    ? "border-error"
                    : beat.phase === "after"
                      ? "border-success"
                      : "border-primary"
                }`}
              >
                <div className="card-body p-4 gap-2">
                  <div className="flex items-baseline justify-between flex-wrap gap-2">
                    <span className="text-xs uppercase tracking-widest opacity-60 font-mono">{beat.label}</span>
                    <span className="text-xs font-mono opacity-60" aria-label={`${offset} seconds from the start`}>
                      +{offset.toFixed(3)}s
                    </span>
                  </div>

                  <code
                    className={`font-mono text-sm font-semibold break-all ${
                      beat.ok ? "text-success" : "text-error"
                    }`}
                  >
                    {beat.status}
                  </code>

                  <p className="text-sm opacity-80 m-0">{beat.note}</p>

                  <div className="flex items-center justify-between flex-wrap gap-2 mt-1">
                    <span className="font-mono text-xs opacity-70">
                      {beat.tokensMoved ?? "no token transfers attached"}
                    </span>
                    <a
                      href={hashscanUrl(beat.transactionId)}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="link link-hover text-xs font-mono"
                    >
                      verify on HashScan ↗
                    </a>
                  </div>
                </div>
              </div>
            </li>
          );
        })}
      </ol>

      <p className="text-xs opacity-60 mt-3">
        Token <code className="font-mono">{EVIDENCE_TOKEN.id}</code> ({EVIDENCE_TOKEN.symbol},{" "}
        {EVIDENCE_TOKEN.decimals} decimals — deliberately not 8) sent from{" "}
        <code className="font-mono">{EVIDENCE_ACCOUNTS.sender}</code> to{" "}
        <code className="font-mono">{EVIDENCE_ACCOUNTS.recipient}</code>, an account created with zero automatic
        association slots. Ordered by consensus timestamp, not by transaction id — under concurrency those two
        disagree.
      </p>
    </section>
  );
};
