/**
 * The three-beat proof.
 *
 * The same token transfer, to the same account, before and after the kit
 * associated the token. Three real transactions on Hedera testnet, one second
 * apart, all verifiable on HashScan.
 *
 * ---------------------------------------------------------------------------
 * THIS FILE CONTAINS NO INVENTED DATA.
 *
 * Every value below is transcribed from `EVIDENCE.md` at the repository root,
 * which is generated by `yarn hardhat:evidence` against live testnet. If you
 * re-run that script the transaction ids change, and this file must be updated
 * with them. Do not edit a timestamp, a status or an amount here to make the UI
 * read better — the entire point of this template is that its claims are
 * checkable, and a fabricated proof panel would be worse than no proof panel.
 *
 * The elapsed time is DERIVED from the consensus timestamps below, never
 * hard-coded, so it cannot drift away from the transactions it describes.
 * ---------------------------------------------------------------------------
 *
 * On the timestamps: a Hedera transaction id carries the timestamp the CLIENT
 * assigned when it built the transaction, not when the network reached
 * consensus. Under concurrency those ids are not in chronological order. The
 * `consensus` field is the network's own ordering and the only one that means
 * anything, so it is what the UI sorts and subtracts.
 *
 * Framework-free. See AGENTS.md.
 */

/** One beat of the proof. */
export interface EvidenceBeat {
  /** Ordering and intent. */
  phase: "before" | "act" | "after";
  /** Short label for the UI. */
  label: string;
  /** Real transaction id — links to HashScan. */
  transactionId: string;
  /**
   * Consensus timestamp, seconds-and-fraction within the run's epoch window.
   * EVIDENCE.md prints these truncated (`…092.918`); the truncation is
   * cosmetic and the ordering and differences are exact.
   */
  consensus: number;
  /** Network response code, verbatim. */
  status: string;
  /** Did the network accept it. */
  ok: boolean;
  /** Token movement, or null when nothing moved. */
  tokensMoved: string | null;
  /** One sentence a reader can check against HashScan. */
  note: string;
}

/** The token used for the run — 2 decimals, deliberately not 8. */
export const EVIDENCE_TOKEN = { id: "0.0.10620849", symbol: "OKE", decimals: 2 } as const;

/** Sender (deployer) and the recipient created with zero auto-association slots. */
export const EVIDENCE_ACCOUNTS = { sender: "0.0.10505627", recipient: "0.0.10620850" } as const;

/**
 * The three beats, in consensus order.
 * Source: EVIDENCE.md § "The pair that matters".
 */
export const EVIDENCE_BEATS: readonly EvidenceBeat[] = [
  {
    phase: "before",
    label: "Before",
    transactionId: "0.0.10505627-1789836087-477565839",
    consensus: 92.918,
    status: "TOKEN_NOT_ASSOCIATED_TO_ACCOUNT",
    ok: false,
    tokensMoved: null,
    note: "Zero token transfers are attached. Nothing moved, and the sender still paid the fee.",
  },
  {
    phase: "act",
    label: "The kit acts",
    transactionId: "0.0.10505627-1789836088-273241870",
    consensus: 93.938,
    status: "SUCCESS",
    ok: true,
    tokensMoved: null,
    note: "Explicit association. The recipient could sign and held HBAR, so this was the cheapest correct path of the four.",
  },
  {
    phase: "after",
    label: "After",
    transactionId: "0.0.10505627-1789836090-275408686",
    consensus: 95.284,
    status: "SUCCESS",
    ok: true,
    tokensMoved: "0.0.10505627 −100 → 0.0.10620850 +100",
    note: "The identical transfer, to the identical account. The only thing that changed is the association.",
  },
] as const;

/**
 * Seconds between the failed transfer and the successful one, derived from
 * consensus timestamps. Never hard-code this.
 */
export function evidenceElapsedSeconds(beats: readonly EvidenceBeat[] = EVIDENCE_BEATS): number {
  if (beats.length < 2) return 0;
  const consensus = beats.map(beat => beat.consensus);
  return Math.round((Math.max(...consensus) - Math.min(...consensus)) * 1000) / 1000;
}

/** Offset of a beat from the first, in seconds. Used to label the timeline. */
export function evidenceOffsetSeconds(beat: EvidenceBeat, beats: readonly EvidenceBeat[] = EVIDENCE_BEATS): number {
  const first = Math.min(...beats.map(b => b.consensus));
  return Math.round((beat.consensus - first) * 1000) / 1000;
}
